all:
  hosts:
      poetry.planetary.pub:
      gardening.planetary.pub:
      fungi.planetary.pub:
      cooking.planetary.pub:
      floss.planetary.pub:
      crypto.planetary.pub:
      queer.family:

      espanol.planetary.pub:
      russian-language.planetary.pub:
      ukrainian-language.planetary.pub:
      chinese-language.planetary.pub:
      french-language.planetary.pub:

      one.planetary.pub:
        ssb-server-branch: disable-ebt
      two.planetary.pub:
        ssb-server-branch: disable-ebt
      three.planetary.pub:
      four.planetary.pub:

      planetary.rocks:

      civic.love:
      planetary.name:
  vars:
    ansible_user: root

  children:
    pubs:
      children:
        system:
          hosts:
            one.planetary.pub:
            two.planetary.pub:
            three.planetary.pub:
            four.planetary.pub:
        language:
          hosts:
            espanol.planetary.pub:
            russian-language.planetary.pub:
            ukrainian-language.planetary.pub:
            french-language.planetary.pub:
            chinese-language.planetary.pub:
        topical:
          hosts:
            poetry.planetary.pub:
            gardening.planetary.pub:
            fungi.planetary.pub:
            cooking.planetary.pub:
            floss.planetary.pub:
            crypto.planetary.pub:
            queer.family:
          vars:
            hops: 1

    oasis:
      hosts:
        planetary.rocks
    viewer:
      hosts:
        # planetary.link
        159.203.117.239
    rooms:
      hosts:
        civic.love:
        planetary.name:
