all:
  hosts:
      poetry.planetary.pub:
      gardening.planetary.pub:
      fungi.planetary.pub:
      cooking.planetary.pub:
      floss.planetary.pub:
      crypto.planetary.pub:
      queer.family:

      espanol.planetary.pub:
      russian-language.planetary.pub:
      ukrainian-language.planetary.pub:
      chinese-language.planetary.pub:
      french-language.planetary.pub:

      one.planetary.pub:
      two.planetary.pub:
      three.planetary.pub:
      four.planetary.pub:

      planetary.rocks:

      civic.love:

      # commented out because this server has had some manual changes made that would be overwritten if the ansible role is run.
      # Talk to @boreq if you need to make changes. See also: https://github.com/planetary-social/infrastructure/issues/28
      #planetary.name:

      graphql.planetary.pub:


  vars:
    ansible_user: root

  children:
    pubs:
      children:
        system:
          hosts:
            one.planetary.pub:
            two.planetary.pub:
            three.planetary.pub:
            four.planetary.pub:
        topical:
          hosts:
            poetry.planetary.pub:
            gardening.planetary.pub:
            fungi.planetary.pub:
            cooking.planetary.pub:
            floss.planetary.pub:
            crypto.planetary.pub:
            queer.family:
          vars:
            hops: 1
        language:
          hosts:
            espanol.planetary.pub:
            russian-language.planetary.pub:
            ukrainian-language.planetary.pub:
            french-language.planetary.pub:
            chinese-language.planetary.pub:

    oasis:
      hosts:
        planetary.rocks
    viewer:
      hosts:
        # planetary.link
        159.203.117.239
    rooms:
      hosts:
        # civic.love:
        # planetary.name:
    rooms2:
      hosts:
        24.199.82.80
    graphql:
      # used by the rooms UI
      hosts:
        graphql.planetary.pub

    letsencrypt:
      hosts:
        graphql.planetary.pub
