---
- name: Ensure room dir exists
  ansible.builtin.file:
    path: /root/go-ssb-room
    state: directory
    mode: '0755'


- name: Copy docker-compose.yml to room dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: /root/go-ssb-room/docker-compose.yml
    mode: 0644


- name: Start up admin
  community.docker.docker_compose:
    project_src: /root/go-ssb-room
    build: false
    restarted: true
  register: output


- ansible.builtin.debug:
    var: output
