---
# This role installs planetary-graphql server with SSL

# NOTE! This role depends on go-ssb-room being run first
#
- name: Ensure planetary-graphql dir exists
  ansible.builtin.file:
    path: /root/graphql # we name it this to avoid confusion with the planetary-graphql repo
    state: directory
    mode: '0755'


- name: Get room key from go-ssb-room
  ansible.builtin.shell: "cat secret | jq .id"
  args:
    chdir: /root/room/ssb-go-room-secrets
  register: get_admin_room_key


- set_fact:
    admin_room_key: "{{ get_admin_room_key.stdout|replace('\"','') }}"


- name: Copy docker-compose.yml to graphql dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: /root/graphql/docker-compose.yml
    mode: 0644


- name: Start up planetary-graphql
  community.docker.docker_compose:
    project_src: /root/graphql
    build: false
  register: output


- name: Get graphql key
  ansible.builtin.command:
  args:
    cmd: docker-compose exec -T -e "KEY_LOCATION=/tmp/planetary-graphql/secret" graphql node print-key.js
    chdir: /root/graphql
  register: get_graphql_key


- set_fact:
    graphql_key: "{{ get_graphql_key.stdout|replace('\"','') }}"

- ansible.builtin.debug:
    var: graphql_key

- name: Add graphql as member to room
  ansible.builtin.command:
  args:
    cmd: docker-compose exec -T room /app/cmd/insert-user/insert-user -repo /ssb-go-room-secrets -role admin -password {{graphql_password}} {{ graphql_key }}
    chdir: /root/room

- name: Retart up planetary-graphql
  community.docker.docker_compose:
    project_src: /root/graphql
    build: false
    restarted: true
  register: output
