---
# This role installs planetary-graphql server with SSL

# Pre-steps
# 1. spin up a droplet, adding SSH keys
# 2. assign a "reserved IP address" (static address)
# 3. add the Droplet to /prod-inventory.yml

# This role depends on go-ssb-room being run first
- name: Ensure planetary-graphql dir exists
  ansible.builtin.file:
    path: /root/planetary-graphql
    state: directory
    mode: '0755'


- name: Get room key from go-ssb-room
  ansible.builtin.shell: "cat secret | jq .id"
  args:
    chdir: /root/go-ssb-room/ssb-go-room-secrets
  register: get_admin_room_key


- set_fact:
    admin_room_key: "{{ get_admin_room_key.stdout|replace('\"','') }}"


- name: Copy docker-compose.yml to planetary-graphql dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: /root/planetary-graphql/docker-compose.yml
    mode: 0644


- name: Start up planetary-graphql
  community.docker.docker_compose:
    project_src: /root/planetary-graphql
    build: false
    restarted: true
  register: output


- name: Get graphql key
  ansible.builtin.command:
  args:
    cmd: docker-compose exec -T -e "KEY_LOCATION=/tmp/planetary-graphql/secret" graphql node print-key.js
    chdir: /root/planetary-graphql
  register: get_graphql_key


- set_fact:
    graphql_key: "{{ get_graphql_key.stdout|replace('\"','') }}"

- ansible.builtin.debug:
    var: graphql_key

- name: Add graphql as member to room
  ansible.builtin.command:
  args:
    cmd: docker-compose exec -T room /app/cmd/insert-user/insert-user -repo /ssb-go-room-secrets -role admin -password admin {{ graphql_key }}
    chdir: /root/go-ssb-room
