---
# This role installs ssb-server on a Debian/Ubuntu server

- name: Create sbot convenience script
  template: src=sbot dest=sbot mode=u+x
- name: Build ssb-server container
  command: "docker build https://github.com/planetary-social/ssb-server.git#main -t planetary-social/ssb-pub"

# Start by shutting down running services
- name: Stop sbot container
  docker_container:
    name: sbot
    state: absent
- name: Stop healer container
  docker_container:
    name: healer
    state: absent

- name: Create ssb-server configuration directory
  ansible.builtin.file:
    path: ~/ssb-pub-data
    state: directory
    owner: 1000
    group: 1000

- name: Create ssb-server configuration file
  template: src=config.j2 dest=~/ssb-pub-data/config

# Run
- name: Start ssb-server
  command: "docker run -d --name sbot -v ~/ssb-pub-data/:/home/node/.ssb/ -p 8008:8008 --restart unless-stopped --memory 3948060160 planetary-social/ssb-pub"
- name: Start healer
  command: "docker run -d --name healer -v /var/run/docker.sock:/tmp/docker.sock --restart unless-stopped ahdinosaur/healer"

# Test
- name: Ensure container is running
  command: "./sbot whoami"
