---
# This role installs ssb-server on a Debian/Ubuntu server

- name: Create sbot convenience script
  template: src=sbot dest=sbot mode=u+x
- name: Build ssb-server container
  command: "docker build https://github.com/planetary-social/ssb-server.git#{{ ssb_server_branch | default('main') }} -t planetary-social/ssb-pub"

- name: Create start script
  template: 
    src: start-sbot 
    dest: ~/start-sbot
    mode: 700

- name: Create stop script
  template: 
    src: stop-sbot 
    dest: ~/stop-sbot
    mode: 700

# Start by shutting down running services
- name: Stop sbot container
  docker_container:
    name: sbot
    state: absent
- name: Stop healer container
  docker_container:
    name: healer
    state: absent

- name: Create ssb-server configuration directory
  ansible.builtin.file:
    path: ~/ssb-pub-data
    state: directory
    owner: 1000
    group: 1000

- name: Create ssb-server configuration file
  template: src=config.j2 dest=~/ssb-pub-data/config

# Run
- name: Start ssb-server
  shell: ~/start-sbot

# Test
- name: Ensure container is running
  command: "./sbot whoami"
