---
# This role installs go-ssb-room on a Debian/Ubuntu server
#
- name: Check out go-ssb-room repo vue branch
  git:
    repo: https://github.com/planetary-social/go-ssb-room.git
    dest: go-ssb-room
    force: yes
    version: vue

- name: Create room configuration file
  template: src=room-env dest=go-ssb-room/env

- name: Copy custom docker-compose.yml
  template: src=docker-compose.yml dest=go-ssb-room/docker-compose.yml

- name: Bring up docker containers
  docker_compose:
    project_src: go-ssb-room
    # build:  yes
    state: present