- name: Install aptitude using apt
  ansible.builtin.apt:
    name: aptitude
    state: latest
    update_cache: no
    force_apt_get: no


- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600


- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: yes


- name: "Disable Snapd Service"
  ansible.builtin.service:
    name: snapd
    state: stopped
    enabled: false


- name: "Uninstall Snapd"
  ansible.builtin.apt:
    pkg: snapd
    state: absent


- name: "Remove Snapd directory"
  ansible.builtin.file:
    path: /root/snap
    state: absent


- name: Install common packages
  ansible.builtin.apt:
    pkg:
      - curl
      - vim
      - git
      - ufw
      - rsync
      - jq
      - tmux
      - mosh
    state: latest
    update_cache: true
    cache_valid_time: 3600


- name: Update and upgrade all installed packages
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600


- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file


- name: Reboot the server (if required).
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true
