- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: no
    force_apt_get: no


- name: Remove old Digital Ocean Repository
  file:
    path: /etc/apt/sources.list.d/droplet-agent.list
    state: absent


- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes


- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: yes


- name: Install common packages
  apt:
    pkg:
      - curl
      - vim
      - git
      - ufw
      - rsync
      - jq
      - tmux
    state: latest
    update_cache: true


- name: Update and upgrade all installed packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes


- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file


- name: Reboot the server (if required).
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true
