- name: Remove old docker packages
  apt:
    name: docker docker-engine docker.io containerd runc
    state: absent    

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python/Ansible
  pip:
    executable: pip3
    name: 
      - docker
      - docker-compose
    
- name: Use Python 3
  command: "update-alternatives --install /usr/bin/python python /usr/bin/python3 1"
